name:  Combined Workflow

on:
  workflow_dispatch:

jobs:
  SonarScan: 
    uses: ./.github/workflows/BuildScan.yml
    secrets: inherit

  CodeQL: 
    uses: ./.github/workflows/codeql-analysis.yml
    secrets: inherit

  SonarJIRA:
        needs: SonarScan
        uses: ./.github/workflows/Python_JIRA.yml
        secrets: inherit
