name: hello-world
on: push
jobs:
  dotnet:
    name: dotnet-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - run: |
          dotnet run
